# Generated by Django 4.0.1 on 2022-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_Stats', '0002_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='language',
            field=models.CharField(default='Hindi', max_length=10),
        ),
    ]
